import { Inter, JetBrains_Mono } from "next/font/google";
import "@/frontend/styles/globals.css";
import { NavigateProvider } from "@/frontend/hooks/useNavigate";
import { AuthProvider } from "@/frontend/hooks/useAuth";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavigateProvider>
          {children}
        </NavigateProvider>
        </AuthProvider>
      </body>
    </html>
  );
}